### ISSUE TITLE
Inspect / copy environment variables of pod

### ISSUE THREAD

**Issue by alexgeek** [aylei/kubectl-debug#102]
Hello,

Is there a way to look at the values of the environment variables on the pod being debugged and/or source them so that the debug container has the same environment?

Thanks,
Alex

**Comment by dm3ch** [comment]
I have imported environment variables of container into debug session using next command:
```
while IFS= read -rd '' var; do export "$var"; done </proc/1/environ
```

**Comment by alexgeek** [comment]
ah nice, thank you!
