### ISSUE TITLE
run debug with mount opts

### ISSUE THREAD

**Issue by runzexia** [aylei/kubectl-debug#110]
Thank you for writing this tool.
I want to add a new function to mount the host's directory into debug container.
Tools such as bcc tools need to mount the host directory to use。
ref https://github.com/iovisor/bcc/blob/c2e2a26b8624492018a14d5eebd4a50b869c911f/QUICKSTART.md#quick-start-guide

**Comment by chengfen1987** [comment]
It's a good idea to debug by bcc.

**Comment by johnmarcou** [comment]
You can browse via /proc:
```
cd /proc/1/root/
```
