### ISSUE TITLE
Doesn't work if HostIP is not directly accessible

### ISSUE THREAD

**Issue by random-ua** [aylei/kubectl-debug#13]
I tried to use kubectl-debug in Kubernetes on MacOS Docker Desktop. Its kubelet is running inside hyperkit vm and have IP that is inaccessible from host machine where kubectl is running. So kubectl-debug "fails with error execute remote, error sending request: Post http://192.168.65.3:10027/api/v1/debug.... : dial tcp 192.168.65.3:10027: connect: operation timed out"

I suppose it also won't work in production envs where kubelet nodes doesn't have external IP or have everything except kubernetes internal traffic blocked at firewall.

One possible solution is to connect to agent via kubectl port-foward if some option is given in command line. Or allow to specify agent endpoint URL either directly in command line or in debug-config (where endpoint overrides can be specified as map nodename => endpoint-uri)

**Comment by aylei** [comment]
Thanks! This issue will be addressed in next release

**Comment by aylei** [comment]
close via #26 and v0.1.0 release
