### ISSUE TITLE
Error: No such image

### ISSUE THREAD

**Issue by wajika** [aylei/kubectl-debug#133]
没有使用daemonset的方式。 直接下载了二进制文件。
我是在master上执行的，pod在某个node上。
第一次报错Error: No such image，我在pod对应的node上也docker pull了image。
第二次启动还是报错Error: No such image。
master执行的位置已经安装了image。

# kubectl debug myapp-deploy-7d574d56c7-clpzv
Agent Pod info: [Name:debug-agent-pod-cff9af34-314f-11eb-8e41-005056ba3a98, Namespace:default, Image:aylei/debug-agent:latest, HostPort:10027, ContainerPort:10027]
Waiting for pod debug-agent-pod-cff9af34-314f-11eb-8e41-005056ba3a98 to run...
Forwarding from 127.0.0.1:10027 -> 10027
Forwarding from [::1]:10027 -> 10027
Handling connection for 10027
                             Start deleting agent pod myapp-deploy-7d574d56c7-clpzv 
error execute remote, Internal error occurred: error attaching to container: Error: No such image: docker.io/nicolaka/netshoot:latest
error: Internal error occurred: error attaching to container: Error: No such image: docker.io/nicolaka/netshoot:latest

**Comment by aylei** [comment]
Duplicate with #134 

Please refer to https://github.com/aylei/kubectl-debug/issues/134#issuecomment-742541850

**Comment by wajika** [comment]
> Duplicate with #134
> 
> Please refer to [#134 (comment)](https://github.com/aylei/kubectl-debug/issues/134#issuecomment-742541850)

thanks
