### ISSUE TITLE
cannot get the debug docker image No such image: docker.io/nicolaka/netshoot:latest

### ISSUE THREAD

**Issue by melochale** [aylei/kubectl-debug#141]
error execute remote, Internal error occurred: error attaching to container: Error: No such image: docker.io/nicolaka/netshoot:latest
error: Internal error occurred: error attaching to container: Error: No such image: docker.io/nicolaka/netshoot:latest

**Comment by weiwarren** [comment]
An unstable debug agent was introduced, use the previous stable version. [133](https://github.com/aylei/kubectl-debug/issues/133), [134](https://github.com/aylei/kubectl-debug/issues/134)
[135](https://github.com/aylei/kubectl-debug/issues/135)


`kubectl  debug nginx --agent-image=aylei/debug-agent:v0.1.1`

**Comment by melochale** [comment]
many thanks, it works!
