### ISSUE TITLE
Warning about missing config

### ISSUE THREAD

**Issue by jacobtomlinson** [aylei/kubectl-debug#22]
Awesome project!

I've followed the install instructions but it always complains about the config not being there.

```
$ kubectl debug mypod
2019/03/13 08:45:32 error loading file  open /Users/jacob/.kube/debug-config: no such file or directory
```

Would be nice for this to be created automatically.

**Comment by aylei** [comment]
Good catch, thanks!

**Comment by aylei** [comment]
close via #27
