### ISSUE TITLE
adapt to CRI

### ISSUE THREAD

**Issue by aylei** [aylei/kubectl-debug#3]
`kubectl-debug` only support docker as container runtime now. We should use CRI for container operations.

**Comment by viczt** [comment]
Hi! Any progress with CRI?

**Comment by aylei** [comment]
> Hi! Any progress with CRI?

Thanks for the ping😜, this work has not yet been started. And hopefully I will have time to work on this in Mar😄

**Comment by aylei** [comment]
I think #99 fixes this, though we did adopt CRI but we effectively abstract an interface of different container runtime
