### ISSUE TITLE
Document the agentless mode

### ISSUE THREAD

**Issue by aylei** [aylei/kubectl-debug#32]
Now that #31 introduced the agentless mode, we should document this feature accordingly.

**Comment by aylei** [comment]
@tkanng Are you interested in documenting this as the feature developer (either chinese/english version)? 

I can do this if you don't have spare time recently.

**Comment by tkanng** [comment]
It's my pleasure. I'll do it this week. :)

**Comment by aylei** [comment]
close via #33 Thanks @tkanng
