### ISSUE TITLE
kubectl debug [pod_name]  is not support find image from local (imagePullPolicy: IfNotPresent)

### ISSUE THREAD

**Issue by sw1136562366** [aylei/kubectl-debug#39]
kubectl debug [pod_name] 
pulling image %s...
 ImagePull requests the docker host to pull an image from a remote registry.
it is not support use image from local.

**Comment by aylei** [comment]
Yes, according to your configuration, there are 1~2 images to pull:
* the image of `debug-agent`, this is a standard Kubernetes Pod and the behavior is controlled by `imagePullPolicy`
* the image of debug container, this image is pulled in the `debug-agent`, there's no logic to skip the pulling phase now, which may need refinement

**Comment by aylei** [comment]
And thanks for your report!

**Comment by sw1136562366** [comment]
I need to use it in an offline environment, but this problem is holding me back.

**Comment by aylei** [comment]
@sw1136562366 
Sorry for this annoying issue, hopefully I can address it this weekend

**Comment by aylei** [comment]
Workaround: if you have a private registry in the offline environment, you can push the image to this registry and pull from it.

**Comment by sw1136562366** [comment]
I will try it, thanks!

**Comment by aylei** [comment]
@sw1136562366 Let me know if you have any questions then😄
