### ISSUE TITLE
安装好了kubectl-debug后执行命令直接refused

### ISSUE THREAD

**Issue by newgoo** [aylei/kubectl-debug#42]
通过二进制文件下载好后在调用kubectl debug demo 的时候，出了异常
在master上运行的, pod中的镜像使用的是nginx镜像
是我在某个服务没有启用吗？

异常内容：
`error execute remote, error sending request: Post http://10.211.55.112:10027/api/v1/debug?command=%5B%22bash%22%5D&container=docker%3A%2F%2F6a6200df293ff1270e809ca14f384a2de72b8a1b02eb262206b5916802a71609&image=nicolaka%2Fnetshoot%3Alatest: dial tcp 10.211.55.112:10027: connect: connection refused
error: error sending request: Post http://10.211.55.112:10027/api/v1/debug?command=%5B%22bash%22%5D&container=docker%3A%2F%2F6a6200df293ff1270e809ca14f384a2de72b8a1b02eb262206b5916802a71609&image=nicolaka%2Fnetshoot%3Alatest: dial tcp 10.211.55.112:10027: connect: connection refused`

**Comment by aylei** [comment]
假如没有装 debug-agent 的话需要使用 `--agentless` 开启无需预先部署代理的模式

**Comment by newgoo** [comment]
好的，问题解决了；

感觉这个工具也太好用了，赞一个👍

**Comment by goerzh** [comment]
我加了 --agentless 参数还是报错
```
kubectl debug tomcat --agentless
Agent Pod info: [Name:debug-agent-pod-2ebbdf45-ee51-11e9-bec4-525400f363fd, Namespace:default, Image:aylei/debug-agent:latest, HostPort:10027, ContainerPort:10027]
Waiting for pod debug-agent-pod-2ebbdf45-ee51-11e9-bec4-525400f363fd to run...
Start deleting agent pod tomcat 
error execute remote, error sending request: Post http://10.1.3.15:10027/api/v1/debug?command=%5B%22bash%22%5D&container=docker%3A%2F%2F35f32873a97b57804dcdcf46445bc32d5bc00464a051a9b567d8ba331b9e0c22&image=nicolaka%2Fnetshoot%3Alatest: dial tcp 10.1.3.15:10027: connect: connection refused
error: error sending request: Post http://10.1.3.15:10027/api/v1/debug?command=%5B%22bash%22%5D&container=docker%3A%2F%2F35f32873a97b57804dcdcf46445bc32d5bc00464a051a9b567d8ba331b9e0c22&image=nicolaka%2Fnetshoot%3Alatest: dial tcp 10.1.3.15:10027: connect: connection refused
```
