### ISSUE TITLE
Macos 使用 brew 安装后报错 找不到这个命令

### ISSUE THREAD

**Issue by vincent927** [aylei/kubectl-debug#43]
![image](https://user-images.githubusercontent.com/10399425/61098615-2b4a9780-a492-11e9-9819-9935da37a51b.png)

**Comment by aylei** [comment]
Could you please provide the output of `kubectl version` ?

**Comment by vincent927** [comment]
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"8cb561c", GitTreeState:"", BuildDate:"2019-04-22T11:34:20Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aylei** [comment]
That make sense, kubectl version prior to `1.12` should use `kubectl-debug` directly instead.

```
$ kubectl-debug -h
```

**Comment by vincent927** [comment]
so because of my kubectl version is too old ?

**Comment by vincent927** [comment]
```
$ kubectl-debug --namespace test pcss-back-base-78667dfbfd-zcnmv -a
Agent Pod info: [Name:debug-agent-pod-116086a8-a452-11e9-908b-a8667f14fb5d, Namespace:default, Image:aylei/debug-agent:latest, HostPort:10027, ContainerPort:10027]
Waiting for pod debug-agent-pod-116086a8-a452-11e9-908b-a8667f14fb5d to run...
Start deleting agent pod pcss-back-base-78667dfbfd-zcnmv
error execute remote, error sending request: Post http://10.0.0.21:10027/api/v1/debug?command=%5B%22bash%22%5D&container=docker%3A%2F%2Ff73eb31fbfdbe3a5ee4647d12b3eb491401534d7400bad818f26d1a0960d6c4d&image=nicolaka%2Fnetshoot%3Alatest: dial tcp 10.0.0.21:10027: connect: operation timed out
error: error sending request: Post http://10.0.0.21:10027/api/v1/debug?command=%5B%22bash%22%5D&container=docker%3A%2F%2Ff73eb31fbfdbe3a5ee4647d12b3eb491401534d7400bad818f26d1a0960d6c4d&image=nicolaka%2Fnetshoot%3Alatest: dial tcp 10.0.0.21:10027: connect: operation timed out
```

**Comment by aylei** [comment]
No, you should enable agentless mode by `--agentless` if you have not instead the `debug-agent` as in advance as stated in README

**Comment by aylei** [comment]
If you don't mind, I will translate the issue title to English so that users who are experiencing the same problem can find this issue more easily.

**Comment by vincent927** [comment]
OK no problem

**Comment by vincent927** [comment]
the pod get my host ip is host internal ip , how can change ?

**Comment by aylei** [comment]
Use `--port-forward` flag to enable port-forward mode, which is host ip agnostic

**Comment by vincent927** [comment]
thanks a lot

**Comment by damienburke** [comment]
am getting this error on kubectl version 1.15.2..

`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}`

**Comment by foobarbecue** [comment]
I'm also getting this on 1.19.3 (which is what @damienburke is also running above -- he was looking at his go version). 

Edit: I upgraded to 1.20 and it works now

**Comment by shreyasiitr** [comment]
I was getting the same for 1.19.7 on windows. Updated to 1.21.1 to fix it.
