### ISSUE TITLE
debug正常运行pod报错

### ISSUE THREAD

**Issue by wuji1mol** [aylei/kubectl-debug#45]
执行：kubectl-debug --namespace test test-pod  --port-forward --agentless
显示：
Agent Pod info: [Name:debug-agent-pod-36a6c112-ad3e-11e9-bd4c-acde48001122, Namespace:default, Image:aylei/debug-agent:latest, HostPort:10027, ContainerPort:10027]
Waiting for pod debug-agent-pod-36a6c112-ad3e-11e9-bd4c-acde48001122 to run...
Error occurred while waiting for pod to run:  pod ran to completion
error: pod ran to completion

**Comment by aylei** [comment]
Seems like that the debug container is not able to run, could you please provide the output of `kubectl get po -n test"?

**Comment by wuji1mol** [comment]
There are  some pods failed to run and one pod running, I delete all the pods and  start debug again, it return to normal.

**Comment by kong62** [comment]
# kubectl debug nginx-5f67f58dd-sr5bz --agentless
Agent Pod info: [Name:debug-agent-pod-9893a803-e0ce-11e9-8d07-5254005a43d2, Namespace:default, Image:aylei/debug-agent:latest, HostPort:10027, ContainerPort:10027]
Waiting for pod debug-agent-pod-9893a803-e0ce-11e9-8d07-5254005a43d2 to run...
Error occurred while waiting for pod to run:  pod ran to completion
error: pod ran to completion


# kubectl logs -f debug-agent-k978d 
2019/09/27 01:59:22 Listening on 0.0.0.0:10027 


 docker ps -l
CONTAINER ID        IMAGE               COMMAND              CREATED                  STATUS                  PORTS               NAMES
cfe504bf99b9        aylei/debug-agent   "/bin/debug-agent"   Less than a second ago   Up Less than a second                       k8s_debug-agent_debug-agent-pod-91134c46-e0cd-11e9-8040-5254005a43d2_default_91142b65-e0cd-11e9-9dd0-5254005a43d2_0
[root@VM_38_3_centos ~]# docker ps -l
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS              PORTS               NAMES
cfe504bf99b9        aylei/debug-agent   "/bin/debug-agent"   1 second ago        Up 1 second                             k8s_debug-agent_debug-agent-pod-91134c46-e0cd-11e9-8040-5254005a43d2_default_91142b65-e0cd-11e9-9dd0-5254005a43d2_0
[root@VM_38_3_centos ~]# docker ps -l
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS                              PORTS               NAMES
cfe504bf99b9        aylei/debug-agent   "/bin/debug-agent"   2 seconds ago       Exited (2) Less than a second ago                       k8s_debug-agent_debug-agent-pod-91134c46-e0cd-11e9-8040-5254005a43d2_default_91142b65-e0cd-11e9-9dd0-5254005a43d2_0
[root@VM_38_3_centos ~]# docker ps -l
CONTAINER ID        IMAGE               COMMAND              CREATED             STATUS                    PORTS               NAMES
cfe504bf99b9        aylei/debug-agent   "/bin/debug-agent"   2 seconds ago       Exited (2) 1 second ago                       k8s_debug-agent_debug-agent-pod-91134c46-e0cd-11e9-8040-5254005a43d2_default_91142b65-e0cd-11e9-9dd0-5254005a43d2_0

**Comment by aylei** [comment]
closed via #67

Please feel free to reopen this issue if the latest version does not fix your problem😉
