### ISSUE TITLE
look like kubernetes will support kubectl debug

### ISSUE THREAD

**Issue by Slach** [aylei/kubectl-debug#48]
Please see
https://github.com/kubernetes/enhancements/issues/277#issuecomment-523395915
https://github.com/verb/kubectl-debug

could you comment which way is better? use your tool? or wait when Ephermal Containers will support?

Could you merge your efforts with other developers?

**Comment by verb** [comment]
We should expect ephemeral containers to be remain in alpha for at least a few release cycles, so there will still be a need for a debugging tool on prod clusters.

**Comment by aylei** [comment]
@Slach Thanks for involving me! I will take a look soon

**Comment by aylei** [comment]
@verb Thanks😉

I have been paying attention to the progress of the native `debug` subcommand and ephemeral containers for a long time, and I believe it is much more mature solution for troubleshooting. But as @verb pointed out, users who maintain old versions of Kubernetes need a debugging tool. So, based on the existing information, I will continue to maintain this repo and guide users of higher Kubernetes versions to the ephemeral containers solution. @Slach
