### ISSUE TITLE
How can i set the docker secret when pulling the nicolaka netshoot image?

### ISSUE THREAD

**Issue by kchenzhi** [aylei/kubectl-debug#53]
In my cluster, nicolaka image is load from my private registry,
It require a secret to pull images, 
but I can't find any docs about setting it.
thanks

**Comment by aylei** [comment]
I'm sorry it is not supported yet, and it is definitely a necessary enhancement.

**Comment by calmkart** [comment]
i'm trying to do this enhancement, probably done in few days

**Comment by aylei** [comment]
@calmkart Sounds good, thanks!

**Comment by kchenzhi** [comment]
@calmkart  anticipating that, thanks for help.

**Comment by calmkart** [comment]
@kchenzhi @aylei fixed in #61 
this issue can closed

**Comment by aylei** [comment]
Thanks! @calmkart
