### ISSUE TITLE
can't resolve dependency issue with go dep

### ISSUE THREAD

**Issue by zouxiang** [aylei/kubectl-debug#54]
When I was trying to run dep init command with kubectl-debug project, I received the following error:

init failed: unable to solve the dependency graph: Solving failure: package github.com/docker/docker/api/types/image does not exist within project githu
b.com/docker/docker

Can you please help how to solve it?

**Comment by aylei** [comment]
This project is using `go mod` now, did you see any documents that guides to `dep`?

**Comment by aylei** [comment]
closed, feel free to reopen this if you have any other questions
