### ISSUE TITLE
使用 --fork 选项不可以启动容器

### ISSUE THREAD

**Issue by sunnoy** [aylei/kubectl-debug#56]
报错

```bash
Error: failed to start container "coredns": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown
```

**Comment by sunnoy** [comment]
对于这种容器是不是无解 。。。

**Comment by aylei** [comment]
AFAIK, there is no general way to keep the process 1 running in a distroless container. I don't know if there are other solutions by far.

**Comment by aylei** [comment]
Will providing an option to specify the start command of the forked container be helpful?
