### ISSUE TITLE
README error

### ISSUE THREAD

**Issue by andreioss** [aylei/kubectl-debug#6]
Hello!
1. You have small mistype here:  

> 
> chmod +x ./kubectl-debug
> mv **kubectdl**-debug /usr/local/bin/  

2. Does `kubectl debug` should work from scratch as you described? Or maybe user should add also bash alias for kubectl-debug executable binary? I've tested your plugin on 1.10 version of cluster and client, and it's completely okay, but only when using just `kubectl-debug` directly.

**Comment by aylei** [comment]
Good catch, thanks!

> Does kubectl debug should work from scratch as you described?
To use `kubectl debug`, kubectl 1.12.0+ is required, otherwise you have to add an alias😅
