### ISSUE TITLE
Forked pod doesn't copy pod's labels

### ISSUE THREAD

**Issue by yarinm** [aylei/kubectl-debug#68]
I have a scenario that I'm using Azure MSI and aad-pod-identity to assign identities to pods (in order to retrieve credentials for several azure services). The way this integration works is by assigning a label to the pods.

When I use the fork feature it doesn't copy any of the original labels and it causes the pod to fail before the point I need to debug.

As I see it, fork should copy the labels of the original pod.

**Comment by calmkart** [comment]
https://github.com/aylei/kubectl-debug/blob/5021027f3806e74a728ced7b69ed6746a237362b/pkg/plugin/cmd.go#L558-L566
is there some reson to strip the labels?

**Comment by aylei** [comment]
@yarinm @calmkart Labels may get Pod operated by Kubernetes controllers. e.g. being adopted by ReplicaSet controller then being deleted because the Pod count exceed the desired replica count, being added to the service endpoints and causing requests to fail.

**Comment by aylei** [comment]
For this scenario I think user should be able to retain certain labels while forking, this can be simply implemented by adding extra command parameters to the debug command. However, this makes the UX more complicated, so I am wondering if there is any better idea.

**Comment by calmkart** [comment]
> 
> 
> For this scenario I think user should be able to retain certain labels while forking, this can be simply implemented by adding extra command parameters to the debug command. However, this makes the UX more complicated, so I am wondering if there is any better idea.

maybe adding a command parameter is a good solution. If there is no better way, I can do this work.

**Comment by calmkart** [comment]
fixed in #69

**Comment by aylei** [comment]
closed via #69
