### ISSUE TITLE
直接执行kubectl debug pod_name  报目标NODE连接拒绝

### ISSUE THREAD

**Issue by a52yth** [aylei/kubectl-debug#71]
MESSAGE:error: error sending request: Post http://172.20.:10027/api/v1/debug?command=%5B%22bash%22%5D&container=docker%3A%2F%2F418d59de3a343e0bef223c6ee5c9c93712ed79bf01ae64324bbd15192f0fe17d&image=nicolaka%2Fnetshoot%3Alatest: dial tcp 172.20.:10027: connect: connection refused

k8s-version：v1.14.3

**Comment by aylei** [comment]
You can use `--port-forward` if the node is inaccessible.

**Comment by aylei** [comment]
#44 will fix this problem

**Comment by aylei** [comment]
closed via #44
