### ISSUE TITLE
Agentless pod does not boot on cluster with CPU and memory restrictions

### ISSUE THREAD

**Issue by lbourdages** [aylei/kubectl-debug#72]
I am having an issue where the agent pod can not be created because it does not specify memory limits/requests. 
For example:
`kubectl debug <pod_name> --agentless --agent-pod-namespace=<namespace>`
Output: 
`Agent Pod info: [Name:debug-agent-pod-<pod_name>, Namespace:<namespace>, Image:aylei/debug-agent:latest, HostPort:10027, ContainerPort:10027]
Error from server (Forbidden): pods "debug-agent-pod-<pod_name>" is forbidden: [maximum memory usage per Pod is 1Ti.  No limit is specified., memory max limit to request ratio per Pod is 2, but no request is specified or request is 0.]`

Our kubernetes cluster enforces restrictions on CPU and memory requests/limits. Any pod without proper limits configured will not be allowed to boot.

It would be nice to allow the CPU and memory parameters to be configured in the config file so we could use the agentless setup.

**Comment by calmkart** [comment]
/assign
i can do this enhancement.

**Comment by calmkart** [comment]
fixed in #73

**Comment by aylei** [comment]
closed via #73
