### ISSUE TITLE
unable to run kubectl-debug

### ISSUE THREAD

**Issue by hillbun** [aylei/kubectl-debug#76]
kubectl-debug traefik-ingress-controller-v2-9vsvk -n kube-system 
error execute remote, error sending request: Post http://192.168.0.183:10027/api/v1/debug?command=%5B%22bash%22%5D&container=docker%3A%2F%2F506c3ea81af0d7887a8c497072439225421392a1730d4fd720a6bb640567967c&image=nicolaka%2Fnetshoot%3Alatest: dial tcp 192.168.0.183:10027: connect: connection refused
error: error sending request: Post http://192.168.0.183:10027/api/v1/debug?command=%5B%22bash%22%5D&container=docker%3A%2F%2F506c3ea81af0d7887a8c497072439225421392a1730d4fd720a6bb640567967c&image=nicolaka%2Fnetshoot%3Alatest: dial tcp 192.168.0.183:10027: connect: connection refused

**Comment by aylei** [comment]
@hillbun Could you please try `kubectl-debug --agentless --port-forward`?

**Comment by hillbun** [comment]
kubectl-debug --agentless --port-forward miop-ui-cf6bff975-9rbbs -n xxxx
               
Agent Pod info: [Name:debug-agent-pod-83566576-f6cd-11e9-a680-fa163e7f9e07, Namespace:default, Image:aylei/debug-agent:latest, HostPort:10027, ContainerPort:10027]
Waiting for pod debug-agent-pod-83566576-f6cd-11e9-a680-fa163e7f9e07 to run...
Error occurred while waiting for pod to run:  pod ran to completion
error: pod ran to completion

**Comment by calmkart** [comment]
@hillbun 
pls try 
`kubectl get pods|grep debug-agent-pod`
if there is more than one agent pod, you should delete all agent pod and try 
`kubectl-debug --agentless --port-forward miop-ui-cf6bff975-9rbbs -n xxxx`
again
if there is just one agent pod and the status is not running.you can 
`kubectl describe <agentPodName>` 
to find the reason.

I think there are probably more than one agent pod here.delete all agent pod will solve it.

**Comment by hillbun** [comment]
it is ok now. thanks

**Comment by arrowfeng** [comment]
> @hillbun Could you please try `kubectl-debug --agentless --port-forward`?
I referenced the document, isn't  supposed to be open by default ?
