### ISSUE TITLE
[INFORMATION SHARE] A web based kubectl tool.

### ISSUE THREAD

**Issue by zhangliqiang** [aylei/kubectl-debug#80]
Hi there,

We developed a web based kubectl tool, which enables you to manage kubernetes credentials and run kubectl command in web browser.

https://github.com/webkubectl/webkubectl

Hopefully it's useful for you guys.

**Comment by aylei** [comment]
Thanks for your sharing! That looks promising.

However, github issue is for bug reporting and feature requesting, closed due to irrelevance, feel free to reopen this issue if you have any problem using `kubectl-debug`.
