### ISSUE TITLE
文档中给的安装方式是失效的，建议修改下

### ISSUE THREAD

**Issue by huangzhiran** [aylei/kubectl-debug#86]
<img width="1166" alt="屏幕快照 2019-12-05 16 23 31" src="https://user-images.githubusercontent.com/30522704/70217746-b8adc180-177c-11ea-87b6-f016b7b6b752.png">

文档中给的安装链接是失效的

**Comment by aylei** [comment]
Hi, 粘贴到部分 terminal 的时候需要注意 terminal 的自动转移, 将 `$\{PLUGIN_VERSION\}` 修改回  `${PLUGIN_VERSION}`即可

**Comment by huangzhiran** [comment]
好的, thanks
