### ISSUE TITLE
关于debug pod的一些疑问

### ISSUE THREAD

**Issue by autherlj** [aylei/kubectl-debug#87]
你好，按照你的教程，我的debug agent pod 和 真实的pod 建立了连接。 可以为什么不可以看到真实POD 的路径下的文件呢？ 只能看到他的java进程，想看日志/log/logs是没有路径的。请问这样是正常的吗？表示只能用一些netstart telnet tcpdump命令不能看真实pod的内容吗？
![error](https://user-images.githubusercontent.com/30717333/70793733-f04ce700-1dd6-11ea-8cc9-94ef34c36b20.png)

**Comment by stockcode** [comment]
The root filesystem of target container is located in /proc/{pid}/root/, and the pid is 1 typically (Pod with sharingProcessNamespace enabled is an exception).

**Comment by aylei** [comment]
Thanks @stockcode
